name: Build
on:
  - push
jobs:
  build_ffmpeg:
    name: Build FFmpeg
    strategy:
      matrix:
        architecture:
          - ARM64
    runs-on:
      - self-hosted
      - linux
      - "${{ matrix.architecture }}"
    container: ghcr.io/sigmaris/ffmpegbuilder:bookworm
    env:
      BASE_VERSION: "7:5.1.2-3"
      RUNNER_ARCH: "${{ matrix.architecture }}"
    steps:
      - name: Determine DEB_ARCH
        run: |
          if [[ "$RUNNER_ARCH" == "ARM" ]]; then
            echo DEB_ARCH=armhf >> $GITHUB_ENV
          else
            echo DEB_ARCH="$(printf '%s' "$RUNNER_ARCH" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: builder-src
      
      - name: Build packages
        run: |
          sudo apt-get update
          rm -rf build
          mkdir build
          cd build
          ../builder-src/prepare.sh
          wget https://github.com/sigmaris/linux/releases/download/6.0.3-rockpro64-ci/linux-libc-dev_6.0.3-g54e50e1b1-sigmaris_arm64.deb
          sudo apt-get -y --allow-downgrades install ./linux-libc-dev_6.0.3-g54e50e1b1-sigmaris_arm64.deb
          rm ./linux-libc-dev_6.0.3-g54e50e1b1-sigmaris_arm64.deb
          ../builder-src/build.sh

      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-debs
          path: build/*.deb

  release:
    runs-on: ubuntu-22.04
    needs: build_ffmpeg
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v3
        with:
          name: ffmpeg-debs
          path: ffmpeg-debs

      - name: Upload packages to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ffmpeg-debs/*
          tag: ${{ github.ref }}
          file_glob: true
