name: Build
on:
  - push
jobs:
  build_ffmpeg:
    name: Build FFmpeg
    strategy:
      matrix:
        architecture:
          - armhf
          - arm64
        include:
          - architecture: armhf
            runner_arch: ARM
            docker_platform: linux/arm/v7
            suffix: "-rpi"
          - architecture: arm64
            runner_arch: ARM64
            docker_platform: linux/arm64
            suffix: ""
    runs-on:
      - self-hosted
      - linux
      - "${{ matrix.runner_arch }}"
    container:
      image: ghcr.io/sigmaris/ffmpegbuilder:bookworm
      options: --platform ${{ matrix.docker_platform }}
    env:
      BASE_VERSION: "7:5.1.3-1"
      DEB_ARCH: "${{ matrix.architecture }}"
      PATCH_DIR: "patches${{ matrix.suffix }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: builder-src
      
      - name: Build packages
        run: |
          sudo apt-get update
          rm -rf build
          mkdir build
          cd build
          ../builder-src/prepare.sh
          if [[ "$DEB_ARCH" == "arm64" ]]; then
            wget https://github.com/sigmaris/linux/releases/download/6.1.23-rockpro64-ci/linux-libc-dev_6.1.23-gcea19e56a-sigmaris_arm64.deb
            sudo apt-get -y --allow-downgrades install ./linux-libc-dev_6.1.23-gcea19e56a-sigmaris_arm64.deb
            rm ./linux-libc-dev_6.1.23-gcea19e56a-sigmaris_arm64.deb
          else
            sudo apt-get -y install linux-libc-dev
          fi
          ../builder-src/build.sh

      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "ffmpeg-debs${{ matrix.suffix }}"
          path: build/*.deb

  release:
    runs-on: ubuntu-22.04
    needs: build_ffmpeg
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v3
        with:
          name: ffmpeg-debs
          path: ffmpeg-debs

      - name: Upload packages to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ffmpeg-debs/*
          tag: ${{ github.ref }}
          file_glob: true
